name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install
        run: |
          npm ci || npm install

      - name: Run build
        run: npm run build

      - name: Mark success
        run: echo "build finished"
